More work

diff --git a/jobs/pgpool/templates/bin/online_recovery b/jobs/pgpool/templates/bin/online_recovery
--- a/jobs/pgpool/templates/bin/online_recovery
+++ b/jobs/pgpool/templates/bin/online_recovery
@@ -5,7 +5,7 @@ postgres_datadir='/var/vcap/store/postgres/db/'
 #Postgres configuration directory
 postgres_configdir='/var/vcap/jobs/postgres/config/'
 #Postgres user ssh key
-postgres_user_key='/var/vcap/jobs/pgpool/id_rsa'
+postgres_user_key='/var/vcap/store/postgres/id_rsa'
 #Pgpool configuration directory
 pgpool_configdir='/var/vcap/jobs/pgpool/config/'
 
@@ -20,10 +20,10 @@ fi
 
 #Get postgres master name
 current_master_name=$(pcp_node_info 10 localhost 9898 postgres postgres $current_master_id | cut -d' ' -f1)
-#Get postgres slave id
-[ $current_master_id == 0 ] && current_slave_id=1 || current_slave_id=0
-#Get postgres slave name
-current_slave_name=$(pcp_node_info 10 localhost 9898 postgres postgres $current_slave_id | cut -d' ' -f1)
+#Get postgres replica id
+[ $current_master_id == 0 ] && current_replica_id=1 || current_replica_id=0
+#Get postgres replica name
+current_replica_name=$(pcp_node_info 10 localhost 9898 postgres postgres $current_replica_id | cut -d' ' -f1)
 
 #Test if pgpool is running
 CheckIfPgpoolIsRunning () {
@@ -44,51 +44,51 @@ AttachNodeToPgpool () {
     done
 }
 
-#Whether the slave node is down, start it and attach it to pgpool's backend pool.
-ReattachDegeneratedSlave () {
-    #Reboot slave node
-    echo "[INFO] Slave node '$current_slave_name' is down. Performing postgres server reboot..."
+#Whether the replica node is down, start it and attach it to pgpool's backend pool.
+ReattachDegeneratedreplica () {
+    #Reboot replica node
+    echo "[INFO] replica node '$current_replica_name' is down. Performing postgres server reboot..."
     #Remote postgres reboot via ssh
-    ssh -i $postgres_user_key vcap@$current_slave_name "touch /tmp/restart_postgres"
+    ssh -i $postgres_user_key vcap@$current_replica_name "sudo /var/vcap/bosh/bin/monit postgresql restart"
     #Test if postgres is running
-    status=$(ssh -i $postgres_user_key vcap@$current_slave_name "if ! killall -0 postgres; then echo 'error'; else echo 'running'; fi;")
+    status=$(ssh -i $postgres_user_key vcap@$current_replica_name "if ! killall -0 postgres; then echo 'error'; else echo 'running'; fi;")
     if [ $status == "error" ]
     then
-        echo "[ERROR] Postgres slave still down !";
+        echo "[ERROR] Postgres replica still down !";
         exit 0;
     else
-        echo "[OK] Slave node successfully started.";
+        echo "[OK] replica node successfully started.";
     fi
 
-    #Do 'slave online recovery' to force slave sync if it has incoherent data relatevely to master.
-    #echo "[INFO] Starting online recovery for slave '$current_slave_name' ..."
-    #ssh -i /var/lib/postgresql/.ssh/id_rsa vcap@$current_slave_name "bash /var/lib/postgresql/streaming-replication.sh $current_master_name"
-    #Atttach slave (even master) to pgpool's backends pool
-    #Reattach the master node if you have performed an online recovery for slave node and not juste a simple reboot. 
+    #Do 'replica online recovery' to force replica sync if it has incoherent data relatevely to master.
+    #echo "[INFO] Starting online recovery for replica '$current_replica_name' ..."
+    #ssh -i /var/lib/postgresql/.ssh/id_rsa vcap@$current_replica_name "bash /var/lib/postgresql/streaming-replication.sh $current_master_name"
+    #Atttach replica (even master) to pgpool's backends pool
+    #Reattach the master node if you have performed an online recovery for replica node and not juste a simple reboot. 
     #Attempting to reatach master to pgpool's backend pool
     #echo "[INFO] Attaching master node '$current_master_name' ..."
     #AttachNodeToPgpool "$current_master_id"
     #echo "[OK] Master node '$current_master_name' has been successfully reattached to pgpool."
-    #Attempting to reattach slave to pgpool's backend pool
-    echo "[INFO] Attaching slave node '$current_slave_name'..."
-    AttachNodeToPgpool "$current_slave_id"
-    echo "[OK] Slave node '$current_slave_name' has been successfully reattached to pgpool."
+    #Attempting to reattach replica to pgpool's backend pool
+    echo "[INFO] Attaching replica node '$current_replica_name'..."
+    AttachNodeToPgpool "$current_replica_id"
+    echo "[OK] replica node '$current_replica_name' has been successfully reattached to pgpool."
 }
 
 
 #Whether the master is down do the folowing operations :
-SwitchOldMasterToSlave () {
+SwitchOldMasterToreplica () {
 
-    new_master_name=$current_slave_name
-    new_master_id=$current_slave_id
-    new_slave_name=$current_master_name
-    new_slave_id=$current_master_id
-    #Setup old master config to slave mode
-    echo "[INFO] Setting up configuration for the new slave node '$new_slave_name'..."
-    ssh -i $postgres_user_key vcap@$new_slave_name "/etc/init.d/postgresql stop"
-    ssh -i $postgres_user_key vcap@$new_slave_name "cp -p $postgres_configdir/postgresql.conf.slave $postgres_configdir/postgresql.conf"
-    ssh -i $postgres_user_key vcap@$new_slave_name  "[ -f $postgres_datadir/recovery.done ] && mv $postgres_datadir/recovery.done $postgres_datadir/recovery.conf"
-    # Switch slave to new master
+    new_master_name=$current_replica_name
+    new_master_id=$current_replica_id
+    new_replica_name=$current_master_name
+    new_replica_id=$current_master_id
+    #Setup old master config to replica mode
+    echo "[INFO] Setting up configuration for the new replica node '$new_replica_name'..."
+    ssh -i $postgres_user_key vcap@$new_replica_name "/etc/init.d/postgresql stop"
+    ssh -i $postgres_user_key vcap@$new_replica_name "cp -p $postgres_configdir/postgresql.conf.replica $postgres_configdir/postgresql.conf"
+    ssh -i $postgres_user_key vcap@$new_replica_name  "[ -f $postgres_datadir/recovery.done ] && mv $postgres_datadir/recovery.done $postgres_datadir/recovery.conf"
+    # Switch replica to new master
     echo "[INFO] Setting up configuration for the new master '$new_master_name'..."
     ssh -i $postgres_user_key vcap@$new_master_name "[ -f /tmp/trigger_file ] && rm /tmp/trigger_file"
     ssh -i $postgres_user_key vcap@$new_master_name "[ -f $postgres_datadir/recovery.conf ] && mv $postgres_datadir/recovery.conf $postgres_datadir/recovery.done"
@@ -103,14 +103,14 @@ SwitchOldMasterToSlave () {
     else
         echo "[OK] New master started.";
     fi
-    # Start new slave/master with online recovery
-    echo "[INFO] Performing online slave recovery..."
-    ssh -i $postgres_user_key vcap@$new_slave_name "bash /var/vcap/jobs/postgres/bin/streaming-replication.sh $new_master_name"
+    # Start new replica/master with online recovery
+    echo "[INFO] Performing online replica recovery..."
+    ssh -i $postgres_user_key vcap@$new_replica_name "bash /var/vcap/jobs/postgres/bin/streaming-replication.sh $new_master_name"
     echo "[OK] Online recovery completed."
 
-    #Write changes to pgpool.conf file to keep the same current master and slave nodes even after pgpool reboot.
+    #Write changes to pgpool.conf file to keep the same current master and replica nodes even after pgpool reboot.
     sed -i "s/^backend_hostname0.*/backend_hostname0='$new_master_name'/" $pgpool_configdir/pgpool.conf
-    sed -i "s/^backend_hostname1.*/backend_hostname1='$new_slave_name'/" $pgpool_configdir/pgpool.conf
+    sed -i "s/^backend_hostname1.*/backend_hostname1='$new_replica_name'/" $pgpool_configdir/pgpool.conf
     echo "[OK] Pgpool configuration file updated."
 
     #Attach new master to pgpool
@@ -118,24 +118,24 @@ SwitchOldMasterToSlave () {
     AttachNodeToPgpool "$new_master_id"
     echo "[OK] New master node '$new_master_name' has been successfully reattached to pgpool."
 
-    #Attach new slave to pgpool
-    echo "[INFO] Attaching new slave node '$new_slave_name'..."
-    AttachNodeToPgpool "$new_slave_id"
-    echo "[OK] New slave node '$new_slave_name' has been successfully reattached to pgpool."
+    #Attach new replica to pgpool
+    echo "[INFO] Attaching new replica node '$new_replica_name'..."
+    AttachNodeToPgpool "$new_replica_id"
+    echo "[OK] New replica node '$new_replica_name' has been successfully reattached to pgpool."
     
 }
 
 CheckIfPgpoolIsRunning
 
-#Get master/slave state
+#Get master/replica state
 current_master_state=$(pcp_node_info 10 localhost 9898 postgres postgres $current_master_id | cut -d' ' -f3)
-current_slave_state=$(pcp_node_info 10 localhost 9898 postgres postgres $current_slave_id | cut -d' ' -f3)
+current_replica_state=$(pcp_node_info 10 localhost 9898 postgres postgres $current_replica_id | cut -d' ' -f3)
 
 # state 1 => postgres server is attached but still not receiving connections
 # state 2 => postgres server is attached and managing clients connections
 # state 3 => postgres server is detached and probably is down.
 
-#If slave is down and master is up then perform an online slave backup.
-[ $current_slave_state == 3 ] && ([ $current_master_state == 1 ] || [ $current_master_state == 2 ]) && ReattachDegeneratedSlave
-#If master is down then switch roles between failed master(new server) and the slave(new master).
-[ $current_master_state == 3 ] && SwitchOldMasterToSlave
+#If replica is down and master is up then perform an online replica backup.
+[ $current_replica_state == 3 ] && ([ $current_master_state == 1 ] || [ $current_master_state == 2 ]) && ReattachDegeneratedreplica
+#If master is down then switch roles between failed master(new server) and the replica(new master).
+[ $current_master_state == 3 ] && SwitchOldMasterToreplica
